export default {
    SAVE_MESSAGES_TO_REDUX:"SAVE_MESSAGES_TO_REDUX",
    REQUIRED_CHATROOM_MESSAGES: "REQUIRED_CHATROOM_MESSAGES",
    SET_MESSAGES_TO_EMPTY: "SET_MESSAGES_TO_EMPTY",
    SEND_TO_FIRE: "SEND_TO_FIRE"
}