export default {
    GET_ALL_USERS: "GET_ALL_USERS",
    GET_CHATS_IDS: "GET_CHATS_IDS",
    LOADING: "LOADING",
    SAVE_MESSAGES_TO_REDUX: "SAVE_MESSAGES_TO_REDUX",
    REQUIRED_CHATROOM_MESSAGES: "REQUIRED_CHATROOM_MESSAGES"
}