export default {
    GET_ALL_USERS: "GET_ALL_USERS",
    GET_CHATS_IDS: "GET_CHATS_IDS",
    LOADING: "LOADING",
    SAVE_MESSAGES_TO_REDUX: "SAVE_MESSAGES_TO_REDUX",
    REQUIRED_CHATROOM_MESSAGES: "REQUIRED_CHATROOM_MESSAGES",
    GET_ALL_CHAT_MESSAGES_FROM_FIRE: "GET_ALL_CHAT_MESSAGES_FROM_FIRE",
    SET_PROFILE_USER:"SET_PROFILE_USER"
}